### ISSUE TITLE
Self-referential GUIDs in Prisma policies

### ISSUE THREAD

**Issue by jasonckeating** [PaloAltoNetworks/terraform-provider-prismacloud#26]
## Describe the bug

The `prismacloud_policy` resource has an attribute `policy_id` in the `compliance_metadata block`.
It is self-referential, (declaring the policy guid, within the policy declaration). 
_This defeats the purpose of a guid if a person manually enters it, and causes the risk of overwriting another policy if the same guid is used. **The Terraform apply will fail if a variable is used to reference the resource block, since it refers to itself.**_

```
lifecycle {
  ignore_changes = [
    # policy_id refers to itself. Unnecessary
    compliance_metadata[0].policy_id
  ]
}
```

## Expected behavior

The policy ID should not require any Terraform to be set, it automatically is created and should only need to be reference by other resources in Terraform.

## Current behavior

Every Terraform run shows that the policy GUID is changing from current to null, causing unnecessary noise (changes) in the deployment logs.

## Possible solution

Remove the need for policy_id in Terraform declaration and stop reporting it as a change.
Make it available as output, after creating the policy.

## Steps to reproduce

Create a Prisma policy.
Leave the policy_id undefined.
Apply the Terraform.
Run the Terraform apply again.
Terraform will want to update the policy_id

## Screenshots
![compliance_metadata updating policy_id](https://user-images.githubusercontent.com/18508669/115270125-a3cb9700-a101-11eb-900a-086608e3938b.png)

**Comment by ebeuerle** [comment]
Fixed in next version.

**Comment by ebeuerle** [comment]
New release being pushed now - can you validate that this fixes the issue?

**Comment by jasonckeating** [comment]
For sure, I'll test as soon as I see the new version.
Still seeing v1.1.1 as the latest release

**Comment by jasonckeating** [comment]
Pulled the new provider v1.1.2 
That took care of the policy_id flip-flopping.

Thanks!!
