### ISSUE TITLE
Notification_config on alert rules are not ignored properly

### ISSUE THREAD

**Issue by phundisk** [PaloAltoNetworks/terraform-provider-prismacloud#7]
## Describe the bug
I have been using terraform to manage alert rules, what policies to add to them and accounts.  The notification configuration section does not seem to be something you can manage within terraform unless you specify the GUID of the "config_id" and GUID of the "recipients" manually.  Because of this, when we manage and create alert rules, we add the lifecycle configuration of ignore_changes on "notification_config", and make those configurations within the web console only.  When we go into the web console, add a notification configuration and then try to do another apply on the config rule (for example due to adding a new policy to the alert rule, we get a 500 error.

Error Log
```
2020/10/16 13:46:24 [WARN] Provider "registry.terraform.io/paloaltonetworks/prismacloud" produced an invalid plan for module.prisma-mastercard-config-policy-alerts.prismacloud_alert_rule.default, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .notification_config: block count in plan (1) disagrees with count in config (0)
2020/10/16 13:46:24 [TRACE] eval: *terraform.EvalCheckPlannedChange
2020/10/16 13:46:24 [TRACE] EvalCheckPlannedChange: Verifying that actual change (action Update) matches planned change (action Update)
2020/10/16 13:46:24 [TRACE] eval: *terraform.EvalGetProvider
2020/10/16 13:46:24 [TRACE] eval: *terraform.EvalReadState
2020/10/16 13:46:24 [TRACE] EvalReadState: reading state for module.prisma-mastercard-config-policy-alerts.prismacloud_alert_rule.default
2020/10/16 13:46:24 [TRACE] UpgradeResourceState: schema version of module.prisma-mastercard-config-policy-alerts.prismacloud_alert_rule.default is still 0; calling provider "prismacloud" for any other minor fixups
2020/10/16 13:46:24 [TRACE] GRPCProvider: UpgradeResourceState
2020/10/16 13:46:24 [TRACE] eval: *terraform.EvalReduceDiff
2020/10/16 13:46:24 [TRACE] eval: *terraform.EvalIf
2020/10/16 13:46:24 [TRACE] eval: terraform.EvalNoop
2020/10/16 13:46:24 [TRACE] eval: *terraform.EvalApplyPre
module.prisma-mastercard-config-policy-alerts.prismacloud_alert_rule.default: Modifying... [id=94386866-7951-4d2d-88f6-98f612fb9337]
2020/10/16 13:46:24 [TRACE] eval: *terraform.EvalApply
2020/10/16 13:46:24 [DEBUG] EvalApply: ProviderMeta config value set
2020/10/16 13:46:24 [DEBUG] module.prisma-mastercard-config-policy-alerts.prismacloud_alert_rule.default: applying the planned Update change
2020/10/16 13:46:24 [TRACE] GRPCProvider: ApplyResourceChange
2020-10-16T13:46:24.314-0500 [DEBUG] plugin.terraform-provider-prismacloud_v1.0.2: 2020/10/16 13:46:24 (update)  alert rule: 94386866-7951-4d2d-88f6-98f612fb9337
2020/10/16 13:46:24 [DEBUG] module.prisma-mastercard-config-policy-alerts.prismacloud_alert_rule.default: apply errored, but we're indicating that via the Error pointer rather than returning it: 500/https://api2.prismacloud.io/alert/rule/94386866-7951-4d2d-88f6-98f612fb9337 Error(msg:internal_error severity:error subject:)
2020/10/16 13:46:24 [TRACE] eval: *terraform.EvalMaybeTainted
2020/10/16 13:46:24 [TRACE] eval: *terraform.EvalWriteState
2020/10/16 13:46:24 [TRACE] EvalWriteState: recording 5 dependencies for module.prisma-mastercard-config-policy-alerts.prismacloud_alert_rule.default
2020/10/16 13:46:24 [TRACE] EvalWriteState: writing current state object for module.prisma-mastercard-config-policy-alerts.prismacloud_alert_rule.default
2020/10/16 13:46:24 [TRACE] eval: *terraform.EvalApplyProvisioners
2020/10/16 13:46:24 [TRACE] EvalApplyProvisioners: prismacloud_alert_rule.default is not freshly-created, so no provisioning is required
2020/10/16 13:46:24 [TRACE] eval: *terraform.EvalMaybeTainted
2020/10/16 13:46:24 [TRACE] eval: *terraform.EvalWriteState
2020/10/16 13:46:24 [TRACE] EvalWriteState: recording 5 dependencies for module.prisma-mastercard-config-policy-alerts.prismacloud_alert_rule.default
2020/10/16 13:46:24 [TRACE] EvalWriteState: writing current state object for module.prisma-mastercard-config-policy-alerts.prismacloud_alert_rule.default
2020/10/16 13:46:24 [TRACE] eval: *terraform.EvalIf
2020/10/16 13:46:24 [TRACE] eval: *terraform.EvalIf
2020/10/16 13:46:24 [TRACE] eval: *terraform.EvalWriteDiff
2020/10/16 13:46:24 [TRACE] eval: *terraform.EvalApplyPost
2020/10/16 13:46:24 [ERROR] eval: *terraform.EvalApplyPost, err: 500/https://api2.prismacloud.io/alert/rule/94386866-7951-4d2d-88f6-98f612fb9337 Error(msg:internal_error severity:error subject:)
2020/10/16 13:46:24 [ERROR] eval: *terraform.EvalSequence, err: 500/https://api2.prismacloud.io/alert/rule/94386866-7951-4d2d-88f6-98f612fb9337 Error(msg:internal_error severity:error subject:)
2020/10/16 13:46:24 [TRACE] [walkApply] Exiting eval tree: module.prisma-mastercard-config-policy-alerts.prismacloud_alert_rule.default
2020/10/16 13:46:24 [TRACE] vertex "module.prisma-mastercard-config-policy-alerts.prismacloud_alert_rule.default": visit complete
2020/10/16 13:46:24 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/10/16 13:46:24 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/paloaltonetworks/prismacloud\"] (close)" errored, so skipping
2020/10/16 13:46:24 [TRACE] dag/walk: upstream of "root" errored, so skipping
```

Ignore lifecycle we use on the alert_rule
```
    lifecycle {
      ignore_changes = [
        notification_config
      ]
    }
```

```
        notification_config {
            config_id           = "94386866-7951-4d2d-88f6-98f612fb9337"
            config_type         = "slack"
            day_of_month        = 1
            detailed_report     = false
            enabled             = true
            frequency           = "as_it_happens"
            hour_of_day         = 0
            include_remediation = false
            last_sent_ts        = 0
            last_updated        = 1602775222559
            recipients          = [
                "80b7cfb9-b580-4973-9f1e-3183c07f9b6a",
            ]
            with_compression    = false

            days_of_week {
                day    = "MO"
                offset = 0
            }
        }
```

## Expected behavior

The plan/apply should work but omit the notification section when talking to the API.  For example, if only the policies are changing, it should only make an API call to update the policies and ignore the notification rule.

## Current behavior
The application process bombs out with a 500 error 

```
Warning: Applied changes may be incomplete

The plan was created with the -target option in effect, so some changes
requested in the configuration may have been ignored and the output values may
not be fully updated. Run the following command to verify that no other
changes are pending:
    terraform plan

Note that the -target option is not suitable for routine use, and is provided
only for exceptional situations such as recovering from errors or mistakes, or
when Terraform specifically suggests to use it as part of an error message.


Error: 500/https://api2.prismacloud.io/alert/rule/94386866-7951-4d2d-88f6-98f612fb9337 Error(msg:internal_error severity:error subject:)

  on ../modules/alert_rule/main.tf line 27, in resource "prismacloud_alert_rule" "default":
  27: resource "prismacloud_alert_rule" "default" {


```

## Possible solution

It is possible that this is a limitation of the Prisma API and not something that can be changed in the module.

## Steps to reproduce

1. Make an alert rule within code
2. Login to the console and modify that alert rule and add a notification policy to it (i.e. slack notification)
3. Make a change to the alert rule in terraform, and then try to apply it

## Your Environment

OSX
Terraform 0.13.2
prismacloud 1.0.2

**Comment by phundisk** [comment]
Actually maybe there is more here.  I think the entire notification_config just does not work.  I tried to add a notification configuration and the API does not seem to take it.  Removing the notification config and creating an empty alert rule seems to work just fine.  Tried multiple combinations, using data sources, static text fields, and this does not create unless the notification_config is just removed entirely. 

```
data "prismacloud_integration" "default" {
    name = "prisma-network-alerts"
}

# data "prismacloud_alert_rule" "default" {
#     name = var.name
# }

resource "prismacloud_alert_rule" "default" {
    name = var.name
    description = var.description
    policies = []
    allow_auto_remediate = var.allow_auto_remediate
    enabled = var.enabled
    scan_all = var.scan_all
    delay_notification_ms = var.delay_notification_ms
    notify_on_open = var.notify_on_open
    notify_on_snoozed = var.notify_on_snoozed
    notify_on_dismissed = var.notify_on_dismissed
    notify_on_resolved = var.notify_on_resolved

    target {
      account_groups = var.account_groups
      excluded_accounts = var.excluded_accounts
      regions = var.regions
    }

    notification_config {
        config_id = "86d66de3-0d33-40cb-ad8c-ecc52dbe7df1"
        config_type = "slack"
        day_of_month = 1
        enabled = true
        frequency = "as_it_happens"
        detailed_report = false
        with_compression = false
        include_remediation = false
        hour_of_day = 0
        recipients = [
            data.prismacloud_integration.default.integration_id
        ]
        days_of_week {
            day = "MO"
            offset = 0
        }
    }
}
```

**Comment by ebeuerle** [comment]
This should be fixed now as of v1.0.7 - please validate.

**Comment by phundisk** [comment]
I will take a look at this this week.

**Comment by phundisk** [comment]
Still getting the same error with the latest provider.  I think its something with the notification config still based on the errors.  I was originally trying to just ignore the notification_configs entirely since there not really a good way to manage them in the prisma provider in the first place using something like that

```
resource "prismacloud_alert_rule" "default" {
    name = var.name
    description = var.description
    policies = concat([ for i in range(length(data.prismacloud_policies.alert_rule_policy_by_label.listing)) : data.prismacloud_policies.alert_rule_policy_by_label.listing[i].policy_id],[ for i in range(length(data.prismacloud_policies.alert_rule_policy_by_label_2.listing)) : data.prismacloud_policies.alert_rule_policy_by_label_2.listing[i].policy_id],[ for i in range(length(data.prismacloud_policies.alert_rule_included_policy_names)) : data.prismacloud_policies.alert_rule_included_policy_names[i].listing[0].policy_id ])
    excluded_policies = [ for i in range(length(data.prismacloud_policies.alert_rule_excluded_policy_names)) : data.prismacloud_policies.alert_rule_excluded_policy_names[i].listing[0].policy_id ]
    allow_auto_remediate = var.allow_auto_remediate
    enabled = var.enabled
    scan_all = var.scan_all
    delay_notification_ms = var.delay_notification_ms
    notify_on_open = var.notify_on_open
    notify_on_snoozed = var.notify_on_snoozed
    notify_on_dismissed = var.notify_on_dismissed
    notify_on_resolved = var.notify_on_resolved

    target {
      account_groups = var.account_groups
      excluded_accounts = var.excluded_accounts
      regions = var.regions
    }

    lifecycle {
      ignore_changes = [
        notification_config
      ]
    }
}
```



Here is me using the latest version:
```
prisma_cloud (master) $ terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Using previously-installed paloaltonetworks/prismacloud v1.0.8
```

Here is what is showing up in my plan (some fields redacted)
```
  # module.prisma-comm-config-policy-alerts.prismacloud_alert_rule.default will be updated in-place
  ~ resource "prismacloud_alert_rule" "default" {
        allow_auto_remediate  = false
        delay_notification_ms = 0
        enabled               = true
        excluded_policies     = []
        id                    = "a380a072-ae18-4732-b9f2-b541c4038adb"
        last_modified_by      = "xxx"
        last_modified_on      = 1604947426138
        name                  = "xxx-policy-alerts"
        notification_channels = []
        notify_on_dismissed   = false
        notify_on_open        = true
        notify_on_resolved    = false
        notify_on_snoozed     = false
        open_alerts_count     = 0
        owner                 = "xxx"
      ~ policies              = [
          + "01316d17-8857-470a-8903-4e20327cc82e",
            "0aee63ef-746d-4437-abe6-af2c3eabd1e3",
            "0b86a171-af05-49f9-9594-ea2e8dcb136a",
            "0f92dae2-3567-40dc-bdd7-497c83b2260e",
            "1170a54b-c9dd-493b-9f54-d984a928477c",
            "12d600c2-cc45-4e7a-94e8-0c391c50c693",
            "13b99e27-aabe-443b-bd4b-6821fe000d13",
            "1416c6f9-433e-4d70-b0e6-2b71b890e914",
            "1b6cd079-88b8-4292-b99c-651d9460755f",
            "1dc97513-b614-4de7-8ab1-2fe66d43ce35",
            "1dec1b1a-5c30-4e65-8191-74846427bbe6",
            "262b7ae6-e51c-4037-8d00-4e365d33eeb8",
            "2922935d-18d8-44a8-a273-f599c7a05553",
            "2bfc9a1e-bbad-4778-8116-99d07f1d2ba5",
            "32456059-9542-4b3b-8647-39e627e5563e",
            "32c1874d-5e85-4410-b6a8-a48e13f91301",
            "33b6a549-f418-45f2-bd9a-e32cfa5bdbfd",
            "39df6f76-fc34-4660-97a1-fc967e3abe33",
            "3d8a0003-1883-476c-a4ad-179494b14e30",
            "3f53dee2-8c94-44dd-885d-962c68cda90f",
            "401110ad-eeff-43a4-8df6-3dfc52a41f9a",
            "4054e5c3-1366-4269-aa67-1e05c192d9c5",
            "425bbcc3-c53c-4218-a001-fd22f0527db1",
            "42e861ba-3ec3-452c-bbec-a3688b1007f9",
            "4316695b-4ecd-49b4-96a9-3863faa4c8b2",
            "4818ccf9-412b-46ba-9e3e-c0e3359b8dcb",
            "58d66df8-38f9-4ba1-b179-e9108141a055",
          + "67d1ff29-f2d5-4ff6-a7fa-c8b09a874197",
            "776fa9f2-4d01-4331-b915-9ed5daf2b676",
            "836a7c8c-34c2-4861-be1e-df2f8cd27aab",
            "8550e271-3cee-413a-99dd-a188c1c741df",
            "988b3f26-6cfe-4d07-812e-ac52c46aa078",
            "acdb81b7-c073-4cf9-a54b-4dfba0557cf9",
            "b5f70bc5-6631-4a1a-afe7-3e02e056396c",
            "ba9c1fca-1d02-492f-9a84-4d7acb2818e8",
            "be17ab89-bebe-4309-8897-75879483401c",
            "c18a894d-ccd8-41f5-aae1-410a592d2a55",
            "c1907ad8-b93d-4597-b219-5369e457172d",
            "c494b791-fbb8-46d4-aa58-fa42add79673",
            "c5b8b9a0-08d3-4415-9d0a-36db7a55fc16",
            "cd2148f6-61bf-4a87-857c-99b7e6183a13",
            "cd8d46ca-4ad0-456f-87af-890b4a63aadc",
            "dd150ea0-bae2-470b-b427-928e841a0aea",
            "dd7588a1-79f0-4b2b-8139-891eb50f570e",
            "dfc8e850-bc2a-469a-a018-5d706e2d977e",
            "e2402231-905f-41c1-bf92-0f1f459c846d",
            "e2f47c0b-e20e-412f-a8c5-2326f9b77d67",
            "e4485075-55df-404b-a0b3-cc753aa39618",
            "e5719dfd-821d-4260-ae2d-575193f62b8e",
            "e8eccfcc-0d46-4044-8124-add33dd54a9f",
            "ec7ba4d9-1ebe-446a-99cc-b9a12d6168c1",
            "ef5c9c91-033c-4de8-ba8e-6e534531d56d",
            "f98083f1-c594-43a0-a603-5e459287a0ea",
            "fed45316-6cae-4dac-aa57-fb451bacb149",
        ]
        policy_labels         = []
        policy_scan_config_id = "a380a072-ae18-4732-b9f2-b541c4038adb"
        read_only             = false
        scan_all              = false

        notification_config {
            config_id           = "a380a072-ae18-4732-b9f2-b541c4038adb"
            config_type         = "slack"
            day_of_month        = 1
            detailed_report     = false
            enabled             = true
            frequency           = "as_it_happens"
            hour_of_day         = 0
            include_remediation = false
            last_sent_ts        = 0
            last_updated        = 1604947426149
            recipients          = [
                "3e069fb1-f7f0-4466-b05a-b7ba2a755cc9",
            ]
            with_compression    = false

            days_of_week {
                day    = "MO"
                offset = 0
            }
        }
        notification_config {
            config_id           = "a380a072-ae18-4732-b9f2-b541c4038adb"
            config_type         = "splunk"
            day_of_month        = 1
            detailed_report     = false
            enabled             = true
            frequency           = "as_it_happens"
            hour_of_day         = 0
            include_remediation = false
            last_sent_ts        = 0
            last_updated        = 1604947426150
            recipients          = [
                "7e09da16-f307-4f79-9a99-d6e883f78afd",
            ]
            with_compression    = false

            days_of_week {
                day    = "MO"
                offset = 0
            }
        }

        target {
            account_groups    = [
                "ed940a06-6844-4c02-a70f-27e2740a2b9d",
                "704f54cc-c946-432e-b1eb-2bdf99fab677",
            ]
            excluded_accounts = []
            regions           = []
        }
    }
```

Still getting a 500 on a rule change with an error that just states ` Error(msg:internal_error severity:error subject:)`
```
module.prisma-comm-config-policy-alerts.prismacloud_alert_rule.default: Modifying... [id=a380a072-ae18-4732-b9f2-b541c4038adb]

Error: 500/https://api2.prismacloud.io/alert/rule/a380a072-ae18-4732-b9f2-b541c4038adb Error(msg:internal_error severity:error subject:)

  on ../modules/alert_rule/main.tf line 27, in resource "prismacloud_alert_rule" "default":
  27: resource "prismacloud_alert_rule" "default" {
```

The debug log still leads me to believe its something with the notification config due to this message ` .notification_config: block count in plan (2) disagrees with count in config (0)`
```
2020-12-03T08:55:10.234-0600 [INFO]  plugin: configuring client automatic mTLS
2020-12-03T08:55:10.257-0600 [DEBUG] plugin: starting plugin: path=.terraform/plugins/registry.terraform.io/paloaltonetworks/prismacloud/1.0.8/darwin_amd64/terraform-provider-prismacloud_v1.0.8 args=[.terraform/plugins/registry.terraform.io/paloaltonetworks/prismacloud/1.0.8/darwin_amd64/terraform-provider-prismacloud_v1.0.8]
2020-12-03T08:55:10.267-0600 [DEBUG] plugin: plugin started: path=.terraform/plugins/registry.terraform.io/paloaltonetworks/prismacloud/1.0.8/darwin_amd64/terraform-provider-prismacloud_v1.0.8 pid=42876
2020-12-03T08:55:10.267-0600 [DEBUG] plugin: waiting for RPC address: path=.terraform/plugins/registry.terraform.io/paloaltonetworks/prismacloud/1.0.8/darwin_amd64/terraform-provider-prismacloud_v1.0.8
2020-12-03T08:55:10.275-0600 [INFO]  plugin.terraform-provider-prismacloud_v1.0.8: configuring server automatic mTLS: timestamp=2020-12-03T08:55:10.275-0600
2020-12-03T08:55:10.298-0600 [DEBUG] plugin: using plugin: version=5
2020-12-03T08:55:10.298-0600 [DEBUG] plugin.terraform-provider-prismacloud_v1.0.8: plugin address: address=/var/folders/pq/cxx2pldd3m1_k328xzmbdznc0000gp/T/plugin478824195 network=unix timestamp=2020-12-03T08:55:10.298-0600
2020-12-03T08:55:10.346-0600 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unimplemented desc = unknown service plugin.GRPCStdio"
2020-12-03T08:55:10.349-0600 [DEBUG] plugin.terraform-provider-prismacloud_v1.0.8: 2020/12/03 08:55:10 (auth) retrieving jwt
2020/12/03 08:55:10 [WARN] Provider "registry.terraform.io/paloaltonetworks/prismacloud" produced an invalid plan for module.prisma-comm-config-policy-alerts.prismacloud_alert_rule.default, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .notification_config: block count in plan (2) disagrees with count in config (0)
module.prisma-comm-config-policy-alerts.prismacloud_alert_rule.default: Modifying... [id=a380a072-ae18-4732-b9f2-b541c4038adb]
2020/12/03 08:55:10 [DEBUG] EvalApply: ProviderMeta config value set
2020/12/03 08:55:10 [DEBUG] module.prisma-comm-config-policy-alerts.prismacloud_alert_rule.default: applying the planned Update change
2020-12-03T08:55:10.891-0600 [DEBUG] plugin.terraform-provider-prismacloud_v1.0.8: 2020/12/03 08:55:10 (update)  alert rule: a380a072-ae18-4732-b9f2-b541c4038adb
2020/12/03 08:55:11 [DEBUG] module.prisma-comm-config-policy-alerts.prismacloud_alert_rule.default: apply errored, but we're indicating that via the Error pointer rather than returning it: 500/https://api2.prismacloud.io/alert/rule/a380a072-ae18-4732-b9f2-b541c4038adb Error(msg:internal_error severity:error subject:)
2020/12/03 08:55:11 [ERROR] eval: *terraform.EvalApplyPost, err: 500/https://api2.prismacloud.io/alert/rule/a380a072-ae18-4732-b9f2-b541c4038adb Error(msg:internal_error severity:error subject:)
2020/12/03 08:55:11 [ERROR] eval: *terraform.EvalSequence, err: 500/https://api2.prismacloud.io/alert/rule/a380a072-ae18-4732-b9f2-b541c4038adb Error(msg:internal_error severity:error subject:)
```

**Comment by sebastian-clearme** [comment]
Any updates on this?

**Comment by ebeuerle** [comment]
We have been unable to reproduce this bug so far...

**Comment by ftbrecordspan** [comment]
Closing due to inactivity
